-- MySQL Script generated by MySQL Workbench
-- Sat Jul  8 11:50:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fitness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fitness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fitness` DEFAULT CHARACTER SET utf8 ;
USE `fitness` ;

-- -----------------------------------------------------
-- Table `fitness`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`member` (
  `id` BIGINT(10) NOT NULL COMMENT '会员id',
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL COMMENT '联系电话',
  `address` VARCHAR(200) NULL COMMENT '地址',
  `sex` CHAR(1) NULL COMMENT '性别',
  `bornDate` DATETIME NULL COMMENT '出生年月',
  `tel` VARCHAR(45) NULL COMMENT '电话',
  `memberCardId` VARCHAR(45) NULL COMMENT '会员卡id',
  `password` VARCHAR(100) NULL COMMENT '密码',
  `age` INT NULL COMMENT '年龄',
  `stadiumId` BIGINT(10) NULL COMMENT '场馆id',
  `nick` VARCHAR(45) NULL COMMENT '昵称',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `memberImgId` VARCHAR(100) NULL COMMENT '头像地址',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `updateDate` DATETIME NULL COMMENT '修改时间',
  `status` CHAR(1) NULL DEFAULT 0 COMMENT '会员状态\n1.正常  2.审核不通过\n3.注销',
  `remark` VARCHAR(500) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`coach` (
  `id` BIGINT(10) NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '姓名',
  `phone` VARCHAR(45) NULL COMMENT '电话',
  `desc` VARCHAR(400) NULL COMMENT '个人描述',
  `stadiumId` BIGINT(10) NULL COMMENT '场馆id',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `updateDate` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`coach_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`coach_job` (
  `id` BIGINT(10) NOT NULL,
  `jobStart` DATETIME NULL COMMENT '工作开始时间',
  `jobEnd` DATETIME NULL COMMENT '工作结束时间',
  `jobDesc` VARCHAR(500) NULL COMMENT '工作描述',
  `coachId` BIGINT(10) NULL COMMENT '教练id',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `updateDate` DATETIME NULL COMMENT '修改时间',
  `status` CHAR(1) NULL COMMENT '状态1 启用 0 停用',
  `jobHead` VARCHAR(45) NULL COMMENT '工作经历title',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`private_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`private_class` (
  `id` BIGINT(10) NOT NULL,
  `classTime` INT NULL COMMENT '教学时长 单位:分',
  `classDesc` VARCHAR(500) NULL COMMENT '课程详情',
  `coachId` BIGINT(10) NULL COMMENT '教练id',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `updateDate` DATETIME NULL COMMENT '修改时间',
  `status` CHAR(1) NULL COMMENT '课程状态  1空闲  0 已预订',
  `startDate` DATETIME NULL COMMENT '开始时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`img` (
  `id` BIGINT(10) NOT NULL,
  `url` VARCHAR(45) NULL COMMENT '图片地址',
  `createDate` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`stadium` (
  `id` INT NOT NULL COMMENT '场馆id',
  `name` VARCHAR(100) NULL COMMENT '场馆名称',
  `address` VARCHAR(500) NULL COMMENT '场馆地址',
  `stadiumImgId` BIGINT(10) NULL COMMENT '场馆图片',
  `content` VARCHAR(500) NULL COMMENT '场馆介绍',
  `city` INT NULL COMMENT '城市编码',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `updateDate` DATETIME NULL COMMENT '更新时间',
  `status` CHAR(1) NULL COMMENT '场馆状态 1 启用 0 停用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`activity` (
  `id` BIGINT(10) NOT NULL COMMENT '活动ID',
  `name` VARCHAR(100) NULL COMMENT '活动名称',
  `content` VARCHAR(500) NULL COMMENT '活动内容',
  `closingDate` DATETIME NULL COMMENT '活动报名截止时间',
  `visitTotal` INT NULL COMMENT '阅读量',
  `stadiumId` BIGINT(10) NULL COMMENT '场馆id',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `startDate` DATETIME NULL COMMENT '活动开始时间',
  `endDate` DATETIME NULL COMMENT '活动结束时间',
  `status` CHAR(1) NULL COMMENT '活动状态',
  `sort` INT NULL COMMENT '排序',
  `updateDate` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`member_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`member_card` (
  `id` BIGINT(10) NOT NULL COMMENT '会员卡id',
  `cardNo` VARCHAR(45) NULL COMMENT '会员卡号',
  `type` VARCHAR(45) NULL COMMENT '会员卡类型\n1.月卡\n2.季卡\n3.半年卡\n4.年卡\n5.次卡',
  `stadiumId` BIGINT(10) NULL COMMENT '场馆ID',
  `startDate` DATETIME NULL COMMENT '有效起始时间',
  `endDate` DATETIME NULL COMMENT '有效结束时间',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `updateDate` DATETIME NULL COMMENT '修改时间',
  `status` CHAR(1) NULL COMMENT '1 正常  0 失效',
  `classTotal` INT NULL COMMENT '课程数量',
  `money` BIGINT(10) NULL COMMENT '会员卡金额',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`health`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`health` (
  `id` BIGINT(10) NOT NULL COMMENT '体测id',
  `memberId` VARCHAR(45) NULL COMMENT '会员id',
  `healthImgId` BIGINT(10) NULL COMMENT '体测图片id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`goup_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`goup_class` (
  `id` BIGINT(10) NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '团课名称',
  `total` INT NULL COMMENT '总人数',
  `address` VARCHAR(100) NULL COMMENT '上课地址',
  `surplusNum` VARCHAR(45) NULL COMMENT '剩余人数',
  `startDate` DATETIME NULL COMMENT '开始时间',
  `endDate` DATETIME NULL COMMENT '结束时间',
  `timeTotal` INT NULL COMMENT '课程时长',
  `status` CHAR(1) NULL COMMENT '团课状态\n1 进行中\n0 未开始',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `updateDate` DATETIME NULL COMMENT '修改时间',
  `groupClassImgId` VARCHAR(45) NULL COMMENT '团课图片',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`member_private_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`member_private_class` (
  `id` BIGINT(10) NOT NULL COMMENT '会员课程表',
  `classId` BIGINT(10) NULL COMMENT '课程id',
  `createDate` DATETIME NULL COMMENT '创建时间',
  `memberId` BIGINT(10) NULL COMMENT '会员id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`member_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`member_class` (
  `id` BIGINT(10) NOT NULL,
  `classId` BIGINT(10) NULL COMMENT '课程id',
  `memberId` VARCHAR(45) NULL COMMENT '会员id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
